GameInfo/authentication/routes.py
from flask import Blueprint, render_template, redirect, request, url_for, flash
from GameInfo.forms import UserSignupForm, UserSigninForm
from GameInfo.models import User, db
from werkzeug.security import check_password_hash
from flask_login import login_user, logout_user, login_required

auth = Blueprint('auth', __name__, template_folder= 'auth_templates')


@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserSignupForm()
    try:
        if request.method == "POST" and form.validate_on_submit():
            first_name = form.first_name.data
            last_name = form.last_name.data
            email = form.email.data
            username = form.username.data
            password = form.password.data

            user = User(first_name, last_name, email, username, password)

            db.session.add(user)
            db.session.commit()

            flash(f'You have succesfully created a user account {email}', "user-created")

            return redirect(url_for('auth.signin'))

    except:
        flash('Invalid Form Data: Please Check Your Form')
        # raise Exception('Invalid Form Data: Please Check Your Form')
        
        
    return render_template('signup.html', form = form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserSigninForm()
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash("you were succesfully logged in via Email/Password","auth-success")
                return redirect(url_for('site.profile'))
    except:
        raise Exception('Invalid Form DATA: please check your form and try again')

    return render_template('signin.html', form = form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

GameInfo/site/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from flask_login import login_required, current_user
from GameInfo.models import db, User, Fav_games 
from GameInfo.forms import BasicSearch, Details, Profile_img, Fav, Fav_delete, UserDataForm
from GameInfo.helpers import f_rel, n_rel, best_, basic_search, get_detalis, tag_filter
import ast  
import cloudinary.uploader
from werkzeug.security import generate_password_hash
import base64

site = Blueprint('site', __name__, template_folder='site_templates') 

@site.route('/', methods =['GET', 'POST'])
def home():
    details_= Details()
    f = tag_filter(f_rel())
    n = tag_filter(n_rel())
    b = tag_filter(best_())
    if request.method == "POST" and details_.validate_on_submit():
        data = details_.id.data
        data_str = base64.b64encode(str(data).encode('utf-8')).decode('utf-8')
        return redirect(url_for('site.details',  data = data_str))
    
    return render_template('index.html', f_rel = f, n_rel = n, best = b, details_=details_)

@site.route('/profile', methods =['GET', 'POST'])
@login_required
def profile():
    user = User.query.filter_by( token = current_user.token).first()
    fav_list = Fav_games.query.filter_by(user_token = current_user.token).all()
    form = Profile_img()
    delete = Fav_delete()
    info = UserDataForm()
    try:
        if request.method == "POST":
            if form.validate_on_submit():
                file = request.files['file']
                response = cloudinary.uploader.upload(file)
                url = response['secure_url']
                user.profile_img = url
                db.session.commit()
                return redirect(url_for('site.profile'))
            if delete.validate_on_submit():  
                Fav_games.query.filter_by(id = delete.id.data).delete()
                db.session.commit()
                return redirect(url_for('site.profile'))
            if info.validate_on_submit():
                user.first_name = info.first_name.data
                user.last_name = info.last_name.data
                user.email = info.email.data
                user.password = generate_password_hash(info.password.data)
                db.session.commit()
                return redirect(url_for('site.profile'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form')
    return render_template('profile.html',form=form,  user=user, fav_list=fav_list, delete=delete, info=info)

@site.route('/search', methods = ['GET','POST'])
@login_required
def search():
    form = BasicSearch()
    details_= Details()
    try:
        if request.method == "POST":
            if form.validate_on_submit():

                name = form.name.data
                result = tag_filter(basic_search(name))
                return render_template('search.html', form=form, data=result, details_=details_)
            elif details_.validate_on_submit():
                data = details_.id.data
                data_str = base64.b64encode(str(data).encode('utf-8')).decode('utf-8')
                return redirect(url_for('site.details',  data = data_str))
        else:
            result = tag_filter(basic_search(" "))
            return render_template('search.html', form=form, details_=details_, data=result)
    except Exception as e:
        raise Exception('Invalid Form Data: Please Check Your Form')

@site.route('/details', methods = ['GET','POST'])
@login_required
def details():
    form = Fav()
    data =  request.args.get('data')
    data = base64.b64decode(data).decode('utf-8')
    res_dict = get_detalis(data)
    fav_list = Fav_games.query.filter_by(user_token = current_user.token).all()
    if request.method == "POST" and form.validate_on_submit():
        form_data = form.data.data
        data_dict=ast.literal_eval(form_data)
        user_token = current_user.token
        for i in fav_list:
            if str(data_dict['id']) == i.rawg_id:
                return redirect(url_for('site.details', data = data))
        rawg_id = data_dict['id']
        name = data_dict['name']
        released = data_dict['released']
        genres = ','.join(i['name'] for i in data_dict['genres'])
        tags = ','.join(i['name'] for i in data_dict['tags'] if i['language'] == "eng")
        img = ','.join(i['image'] for i in data_dict['short_screenshots'])
        website = data_dict['website']
        platforms = ','.join(i['platform']['name'] for i in data_dict['platforms'])
        fav = Fav_games(user_token, rawg_id, name, released, genres, tags, img, website, platforms)
        db.session.add(fav)
        db.session.commit()
        return redirect(url_for('site.profile'))
    return render_template('details.html',form = form, data = res_dict)

@site.route('/test')
def test():
    details_= Details()
    f = tag_filter(f_rel())
    n = tag_filter(n_rel())
    b = tag_filter(best_())
    if request.method == "POST" and details_.validate_on_submit():
        data = details_.id.data
        return redirect(url_for('site.details',  data = data))
    return render_template('test.html', f_rel = f, n_rel = n, best = b, details_=details_)

GameInfo/templates/base.html
<nav class="ct-nav">
    <div>
        <img src="../static/images/logo20.png">
    </div>
    <!--Nac Items -->
    <div id="horizontal-list-wrapper">            
        <ul id="horizontal-list">
          <li><a href="{{ url_for('site.home') }}">Home</a></li>
          {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('site.search') }}">Search</a> </li>
            <li class="dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Menu
                </a>
                <ul class="dropdown-menu" >
                    <li><a href="{{ url_for('site.profile') }}" class="dropdown-item">Profile</a></li>
                    <li><a href="{{ url_for('auth.logout') }}" class="dropdown-item ">Sign Out</a></li>
                </ul>
              </li>
            {% else %}
              <li><a href="{{ url_for('auth.signup') }}">Sign Up</a></li>
              <li><a href="{{ url_for('auth.signin') }}">Sign In</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

GameInfo/templates/footer.html
<footer class="footer">
  <div class="container">
      <section>
        <div class="row first-row">
          <div class="col-md-2">
              <h4>
                  <a href="#!">About us</a>
              </h4>
          </div>
  
          <div class="col-md-2">
              <h4>
                  <a href="#!">Help</a>
              </h4>
          </div>
  
          <div class="col-md-2">
              <h4>
                  <a href="#!">Contact</a>
              </h4>
          </div>
      </section>
      <section>
          <div class="row">
              <div class="col-lg-8">
                  <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Qui ratione quibusdam accusantium quidem ipsam amet
                      aliquid fugit ipsa obcaecati debitis? Consequatur quasi, hic beatae eaque ullam laborum fugiat fugit doloremque?</p>
              </div>
          </div>
      </section>
      <section class="social">
          <div class="row">
              <div class="col-md-2">
                  <a href="https://www.facebook.com/">
                      <i class="fab fa-facebook-f"></i>
                  </a>
              </div>
              <div class="col-md-2">
                  <a href="https://www.twitter.com/">
                      <i class="fab fa-twitter"></i>
                  </a>
              </div>
              <div class="col-md-2">
                  <a href="https://www.instagram.com/">
                      <i class="fab fa-instagram"></i>
                  </a>
              </div>
          </div>
      </section>
  </div>
</footer>

GameInfo/templates/form_details.html
<form method = "POST" >
    {{ details_.hidden_tag() }}
    <fieldset hidden>
        {{ details_.id.label }}
        {{ details_.id(class = "form-control", value=i['id']) }}
    </fieldset>
    {{ details_.submit_button(class = "btn btn-primary btn-block") }}
</form>

GameInfo/templates/form_signin.html
<div class="p-4">

    <form method = "POST">
        {{ form.hidden_tag() }}
        <div class="card">
            <a class="sign">log in</a>
            <div class="inputBox">
                {{ form.email(class = "form-label") }}
                <span class="user">{{ form.email.label }}</span>
            </div>
            <div class="inputBox">
                {{ form.password(class = "form-label") }}
                <span>{{ form.password.label }}</span>
            </div>
            {{ form.submit(class = "enter btn btn-primary btn-blockenter") }}
        </div>
    </form>
    <p style="margin-left: 2%; margin-top: 30px; color: black;">Don't have account? <a href="{{ url_for('auth.signup') }}">click here</a></p>

</div>

<Style>
.sign {
color: #000;
text-transform: uppercase;
letter-spacing: 2px;
display: block;
font-weight: bold;
font-size: x-large;
}

.card {
display: flex;
justify-content: center;
align-items: center;
min-height: 350px;
width: 300px;
flex-direction: column;
gap: 35px;
background: #e3e3e3;
box-shadow: 16px 16px 32px #c8c8c8,
        -16px -16px 32px #fefefe;
border-radius: 8px;
}

.inputBox {
position: relative;
width: 250px;
}

.inputBox .form-label {
width: 100%;
padding: 10px;
outline: none;
border: none;
color: #000;
font-size: 1em;
background: transparent;
border-left: 2px solid #000;
border-bottom: 2px solid #000;
transition: 0.1s;
border-bottom-left-radius: 8px;
}

.inputBox span {
margin-top: 5px;
position: absolute;
left: 0;
transform: translateY(-4px);
margin-left: 10px;
padding: 10px;
pointer-events: none;
font-size: 12px;
color: #000;
text-transform: uppercase;
transition: 0.5s;
letter-spacing: 3px;
border-radius: 8px;
}

.inputBox input:valid~span,
.inputBox input:focus~span {
transform: translateX(113px) translateY(-15px);
font-size: 0.8em;
padding: 5px 10px;
background: #000;
letter-spacing: 0.2em;
color: #fff;
border: 2px;
}

.inputBox input:valid,
.inputBox input:focus {
border: 2px solid #000;
border-radius: 8px;
}

.enter {
height: 45px;
width: 100px;
border-radius: 5px;
border: 2px solid #000;
cursor: pointer;
background-color: transparent;
transition: 0.5s;
text-transform: uppercase;
font-size: 10px;
letter-spacing: 2px;
margin-bottom: 1em;
}

.enter:hover {
background-color: rgb(0, 0, 0);
color: white;
}
p a{
    color: #000;
    text-decoration: none;
}
p a:hover{
    background-color: white;
    color: #ff634b;
    transition: all 1.5s ease;
}
</Style>

GameInfo/templates/form_signup.html
<div class="p-4">
    <form method = "POST">
        {{ form.hidden_tag() }}
        <div class="card">
            <a class="sign">Sign Up</a>
            <div class="inputBox">
                {{ form.first_name(class = "form-label") }}
                <span class="user">{{ form.first_name.label }}</span>
            </div>
            <div class="inputBox">
                {{ form.last_name(class = "form-label") }}
                <span class="user">{{ form.last_name.label }}</span>
            </div>
            <div class="inputBox">
                {{ form.email(class = "form-label") }}
                <span class="user">{{ form.email.label }}</span>
            </div>
            <div class="inputBox">
                {{ form.username(class = "form-label") }}
                <span class="user">{{ form.username.label }}</span>
            </div>
            <div class="inputBox">
                {{ form.password(class = "form-label") }}
                <span>{{ form.password.label }}</span>
            </div>
            {{ form.submit(class = "enter btn btn-primary btn-blockenter") }}
        </div>
    </form>
    <p style="margin-left: 1%; margin-top: 30px; color: black;">Already have an account? <a href="{{ url_for('auth.signin') }}">click here</a></p>
</div>
<Style>
.sign {
color: #000;
text-transform: uppercase;
letter-spacing: 2px;
display: block;
font-weight: bold;
font-size: x-large;
}

.card {
display: flex;
justify-content: center;
align-items: center;
min-height: 350px;
width: 300px;
flex-direction: column;
gap: 35px;
background: #e3e3e3;
box-shadow: 16px 16px 32px #c8c8c8,
        -16px -16px 32px #fefefe;
border-radius: 8px;
}

.inputBox {
position: relative;
width: 250px;
}

.inputBox .form-label {
width: 100%;
padding: 10px;
outline: none;
border: none;
color: #000;
font-size: 1em;
background: transparent;
border-left: 2px solid #000;
border-bottom: 2px solid #000;
transition: 0.1s;
border-bottom-left-radius: 8px;
}

.inputBox span {
margin-top: 5px;
position: absolute;
left: 0;
transform: translateY(-4px);
margin-left: 10px;
padding: 10px;
pointer-events: none;
font-size: 12px;
color: #000;
text-transform: uppercase;
transition: 0.5s;
letter-spacing: 3px;
border-radius: 8px;
}

.inputBox input:valid~span,
.inputBox input:focus~span {
transform: translateX(113px) translateY(-15px);
font-size: 0.8em;
padding: 5px 10px;
background: #000;
letter-spacing: 0.2em;
color: #fff;
border: 2px;
}

.inputBox input:valid,
.inputBox input:focus {
border: 2px solid #000;
border-radius: 8px;
}

.enter {
height: 45px;
width: 100px;
border-radius: 5px;
border: 2px solid #000;
cursor: pointer;
background-color: transparent;
transition: 0.5s;
text-transform: uppercase;
font-size: 10px;
letter-spacing: 2px;
margin-bottom: 1em;
}

.enter:hover {
background-color: rgb(0, 0, 0);
color: white;
}
p a{
    color: #000;
    text-decoration: none;
}
p a:hover{

background-color: white;
color: #ff634b;
transition: all 1.5s ease;
}
</Style>